// Generated by tools/abitable.py from swgemu.exe md5 d84ee5565c24420858972edda9dddbf4. DO NOT EDIT BY HAND.
#pragma once
#include <cstdint>

namespace cp { namespace abi {

static const char EXE_MD5[] = "d84ee5565c24420858972edda9dddbf4";

struct FuncSig { const char* name; uint32_t va; unsigned char sig[8]; };
static const FuncSig FUNCS[] = {
    {"UIManager_gUIManager", 0x0087FF60, {0x55,0x8B,0xEC,0x6A,0xFF,0x68,0x7B,0x5A}},  // cdecl
    {"UIManager_ProcessMessage", 0x010E77C0, {0x55,0x8B,0xEC,0x6A,0xFF,0x68,0x08,0x30}},  // thiscall
    {"UIManager_GetObjectFromPath", 0x010EA7E0, {0x55,0x8B,0xEC,0x8B,0x49,0x04,0x85,0xC9}},  // thiscall
    {"UIManager_GetFocusedLeaf", 0x010EA810, {0x8B,0x49,0x04,0x85,0xC9,0x75,0x03,0x33}},  // thiscall
    {"UIManager_PushContextWidget", 0x010EA050, {0x55,0x8B,0xEC,0x6A,0xFF,0x68,0x3B,0x32}},  // thiscall
    {"UIManager_PopContextWidgets", 0x010EA220, {0x55,0x8B,0xEC,0x6A,0xFF,0x68,0x68,0x32}},  // thiscall
    {"UIManager_AbortDrag", 0x010EA8F0, {0x55,0x8B,0xEC,0x83,0xEC,0x28,0x56,0x8B}},  // thiscall
    {"UIBaseObject_GetObjectFromPath", 0x010F4FA0, {0x55,0x8B,0xEC,0x56,0x57,0x8B,0x7D,0x08}},  // thiscall
    {"UIWidget_SetLocation", 0x01106160, {0x55,0x8B,0xEC,0x83,0xEC,0x10,0x8A,0x45}},  // thiscall
    {"UIText_SetLocalText", 0x0110F580, {0x55,0x8B,0xEC,0x6A,0xFF,0x68,0x10,0x53}},  // thiscall
    {"UIMessage_ctor", 0x01124BF0, {0x8B,0xC1,0x33,0xC9,0x89,0x08,0x88,0x48}},  // thiscall
    {"CuiIoWin_warpCursor", 0x0093D1F0, {0x55,0x8B,0xEC,0x83,0xEC,0x28,0x8B,0x45}},  // thiscall
    {"InputScheme_resetFromType", 0x006E1B40, {0x55,0x8B,0xEC,0x6A,0xFF,0x68,0xE0,0x87}},  // cdecl
    {"CuiActionManager_performAction", 0x008CC460, {0x55,0x8B,0xEC,0xA1,0x98,0xCC,0x89,0x01}},  // cdecl
    {"CuiActionManager_addAction", 0x008CC650, {0x55,0x8B,0xEC,0x6A,0xFF,0x68,0x70,0xEC}},  // cdecl
    {"CuiMediator_getCodeDataObject", 0x00A68210, {0x55,0x8B,0xEC,0x6A,0xFF,0x68,0x9F,0x37}},  // cdecl
    {"runGameLoopOnce", 0x004237C0, {0x55,0x8B,0xEC,0x6A,0xFF,0x68,0x90,0x46}},  // cdecl
    {"Game_getGameInputMap", 0x00425B80, {0xA1,0x5C,0x88,0x90,0x01,0x6A,0x00,0x68}},  // cdecl
    {"CuiInputNames_getInputValueString", 0x009EB770, {0x55,0x8B,0xEC,0x8B,0x45,0x0C,0x8B,0x00}},  // cdecl
    {"Stlp_allocate", 0x012EA770, {0x6A,0xFF,0x68,0x88,0x75,0x5C,0x01,0x64}},  // cdecl
    {"Stlp_deallocate", 0x00424B00, {0x55,0x8B,0xEC,0x8B,0x4D,0x08,0x85,0xC9}},  // thiscall
    {"UIText_SetPreLocalized", 0x01112660, {0x55,0x8B,0xEC,0x53,0x8B,0x5D,0x08,0x56}},  // thiscall
    {"UIVolumePage_Pack", 0x0113C6C0, {0x64,0xA1,0x00,0x00,0x00,0x00,0x6A,0xFF}},  // thiscall
    {"SwgCuiToolbar_getToolbarItem", 0x00F67890, {0x55,0x8B,0xEC,0x56,0x57,0x8B,0x7D,0x0C}},  // thiscall
    {"SwgCuiToolbar_setToolbarItem", 0x00F667C0, {0x55,0x8B,0xEC,0x83,0xEC,0x08,0x8B,0x55}},  // thiscall
    {"Game_getPlayerCreature", 0x00425200, {0xA1,0x5C,0x88,0x90,0x01,0x56,0x6A,0x00}},  // cdecl
    {"ClientWorld_findObjectsInRange", 0x00561980, {0x55,0x8B,0xEC,0x83,0xEC,0x30,0xD9,0x45}},  // cdecl
    {"CuiCombatManager_targetIsAttackable", 0x008C72F0, {0x55,0x8B,0xEC,0x8B,0x4D,0x0C,0x8B,0x01}},  // cdecl
    {"CuiCombatManager_isTargetCycleOk", 0x008C8AB0, {0x55,0x8B,0xEC,0x83,0xEC,0x1C,0x56,0x57}},  // cdecl
    {"TangibleObject_isAttackable", 0x00640220, {0xA0,0x58,0x88,0x90,0x01,0x84,0xC0,0x75}},  // thiscall
    {"CreatureObject_setLookAtTarget", 0x00434AB0, {0x53,0x8B,0xDC,0x83,0xEC,0x08,0x83,0xE4}},  // thiscall
    {"ClientObject_getLocalizedName", 0x00556EC0, {0x56,0x8B,0xF1,0x8A,0x86,0x84,0x01,0x00}},  // thiscall
    {"Object_getNetworkId", 0x00B23C60, {0x8D,0x41,0x20,0xC3,0x90,0x90,0x90,0x90}},  // thiscall
    {"Object_getTransform", 0x00B22C80, {0x56,0x8B,0xF1,0x8B,0x4E,0x34,0x85,0xC9}},  // thiscall
    {"CachedNetworkId_getObject", 0x00B30160, {0x53,0x8B,0xD9,0xE8,0x58,0xFF,0xFF,0xFF}},  // thiscall
    {"ConfigClientGame_getTargetingRange", 0x005034F0, {0xE8,0x7B,0x2C,0xF2,0xFF,0x84,0xC0,0x74}},  // cdecl
    {"Stlp_free_big", 0x00AC1640, {0x55,0x8B,0xEC,0x8B,0x45,0x08,0x85,0xC0}},  // cdecl
    {"Stlp_free_small", 0x012EA920, {0x51,0x8B,0x44,0x24,0x0C,0x53,0x48,0x55}},  // cdecl
};
static const uint32_t UIManager_gUIManager = 0x0087FF60;
static const uint32_t UIManager_ProcessMessage = 0x010E77C0;
static const uint32_t UIManager_GetObjectFromPath = 0x010EA7E0;
static const uint32_t UIManager_GetFocusedLeaf = 0x010EA810;
static const uint32_t UIManager_PushContextWidget = 0x010EA050;
static const uint32_t UIManager_PopContextWidgets = 0x010EA220;
static const uint32_t UIManager_AbortDrag = 0x010EA8F0;
static const uint32_t UIBaseObject_GetObjectFromPath = 0x010F4FA0;
static const uint32_t UIWidget_SetLocation = 0x01106160;
static const uint32_t UIText_SetLocalText = 0x0110F580;
static const uint32_t UIMessage_ctor = 0x01124BF0;
static const uint32_t CuiIoWin_warpCursor = 0x0093D1F0;
static const uint32_t InputScheme_resetFromType = 0x006E1B40;
static const uint32_t CuiActionManager_performAction = 0x008CC460;
static const uint32_t CuiActionManager_addAction = 0x008CC650;
static const uint32_t CuiMediator_getCodeDataObject = 0x00A68210;
static const uint32_t runGameLoopOnce = 0x004237C0;
static const uint32_t Game_getGameInputMap = 0x00425B80;
static const uint32_t CuiInputNames_getInputValueString = 0x009EB770;
static const uint32_t Stlp_allocate = 0x012EA770;
static const uint32_t Stlp_deallocate = 0x00424B00;
static const uint32_t UIText_SetPreLocalized = 0x01112660;
static const uint32_t UIVolumePage_Pack = 0x0113C6C0;
static const uint32_t SwgCuiToolbar_getToolbarItem = 0x00F67890;
static const uint32_t SwgCuiToolbar_setToolbarItem = 0x00F667C0;
static const uint32_t Game_getPlayerCreature = 0x00425200;
static const uint32_t ClientWorld_findObjectsInRange = 0x00561980;
static const uint32_t CuiCombatManager_targetIsAttackable = 0x008C72F0;
static const uint32_t CuiCombatManager_isTargetCycleOk = 0x008C8AB0;
static const uint32_t TangibleObject_isAttackable = 0x00640220;
static const uint32_t CreatureObject_setLookAtTarget = 0x00434AB0;
static const uint32_t ClientObject_getLocalizedName = 0x00556EC0;
static const uint32_t Object_getNetworkId = 0x00B23C60;
static const uint32_t Object_getTransform = 0x00B22C80;
static const uint32_t CachedNetworkId_getObject = 0x00B30160;
static const uint32_t ConfigClientGame_getTargetingRange = 0x005034F0;
static const uint32_t Stlp_free_big = 0x00AC1640;
static const uint32_t Stlp_free_small = 0x012EA920;

static const uint32_t UIManager_gSingleton = 0x01996E98;  // UIManager*; CuiManager::remove deletes through vtbl[1]
static const uint32_t UIManager_gIsPopping = 0x01996E9C;  // the guard in PopContextWidgets
static const uint32_t CuiManager_ms_theIoWin = 0x0192613C;  // a store after the CuiIoWin constructor (0x93ADB0, size 0x68)
static const uint32_t UIMessage_key_BackSpace = 0x018D98E0;  // word
static const uint32_t UIMessage_key_Insert = 0x018D98E2;  // word
static const uint32_t UIMessage_key_Delete = 0x018D98E4;  // word
static const uint32_t UIMessage_key_LeftArrow = 0x018D98E6;  // word
static const uint32_t UIMessage_key_RightArrow = 0x018D98E8;  // word
static const uint32_t UIMessage_key_UpArrow = 0x018D98EA;  // word
static const uint32_t UIMessage_key_DownArrow = 0x018D98EC;  // word
static const uint32_t UIMessage_key_Home = 0x018D98EE;  // word
static const uint32_t UIMessage_key_End = 0x018D98F0;  // word
static const uint32_t UIMessage_key_PageUp = 0x018D98F2;  // word
static const uint32_t UIMessage_key_PageDown = 0x018D98F4;  // word
static const uint32_t UIMessage_key_Tab = 0x018D98F6;  // word
static const uint32_t UIMessage_key_Space = 0x018D98F8;  // word
static const uint32_t UIMessage_key_Enter = 0x018D98FA;  // word
static const uint32_t UIMessage_key_Escape = 0x018D98FC;  // word
static const uint32_t PROP_CmdName = 0x019355B8;  // "CmdName" -> CuiDragInfo::cmd
static const uint32_t PROP_DragInfoName = 0x019355B4;  // "DragInfoName" -> CuiDragInfo::name
static const uint32_t PROP_CmdStr = 0x019355B0;  // "CmdStr" -> CuiDragInfo::str, on a live item this holds "/ache"
static const uint32_t PROP_DragCommandValue = 0x019355AC;  // "DragCommandValue" -> CuiDragInfo::commandValue

static const uint32_t VT_UIWidget = 0x015FA0CC;  // 57 methods
static const uint32_t VT_UIPage = 0x015F9DA4;  // 61 methods
static const uint32_t VT_UIVolumePage = 0x015FB39C;  // 61 methods
static const uint32_t VT_UIButton = 0x015FA2CC;  // 57 methods
static const uint32_t VT_UIImage = 0x015FA4DC;  // 57 methods
static const uint32_t VT_UIText = 0x015FA1D4;  // 57 methods
static const uint32_t VT_UIManager = 0x015F9BBC;  // 2 methods
static const uint32_t VT_UIPopupMenu = 0x015FAAC4;  // 61 methods
static const uint32_t VT_UIRadialMenu = 0x015FA924;  // 61 methods
static const uint32_t VT_UITabbedPane = 0x015FBAA4;  // 61 methods
static const uint32_t VT_UIList = 0x015FB2B4;  // 57 methods
static const uint32_t VT_UICursor = 0x015FABE4;  // 29 methods
static const uint32_t VT_CuiIoWin = 0x015E8618;  // 3 methods
static const uint32_t VT_CuiMediator = 0x015E8EE4;  // 12 methods
static const uint32_t VT_CuiWorkspace = 0x015E9094;  // 2 methods
static const uint32_t VT_SwgCuiToolbar = 0x015F6798;  // 12 methods
static const uint32_t VT_SwgCuiInventory = 0x015F03C0;  // 12 methods
static const uint32_t VT_SwgCuiInventoryContainerIcons = 0x015F73B8;  // 12 methods

static const int SLOT_IsA = 0;
static const int SLOT_GetTypeName = 1;
static const int SLOT_Clone = 2;
static const int SLOT_Destroy = 3;
static const int SLOT_Attach = 4;
static const int SLOT_Detach = 5;
static const int SLOT_GetPropertyNames = 6;
static const int SLOT_GetLinkPropertyNames = 7;
static const int SLOT_RemoveProperty_c = 8;
static const int SLOT_RemoveProperty = 9;
static const int SLOT_SetProperty_c = 10;
static const int SLOT_SetProperty = 11;
static const int SLOT_GetProperty_c = 12;
static const int SLOT_GetProperty = 13;
static const int SLOT_ResetLocalizedStrings = 14;
static const int SLOT_CopyPropertiesFrom = 15;
static const int SLOT_AddChild = 16;
static const int SLOT_RemoveChild = 17;
static const int SLOT_SelectChild = 18;
static const int SLOT_GetChild = 19;
static const int SLOT_GetChildren = 20;
static const int SLOT_GetChildCount = 21;
static const int SLOT_RemoveFromParent = 22;
static const int SLOT_MinimizeResources = 23;
static const int SLOT_CanChildMove = 24;
static const int SLOT_MoveChild = 25;
static const int SLOT_Link = 26;
static const int SLOT_DuplicateObject = 27;
static const int SLOT_dtor = 28;
static const int SLOT_SetRect = 29;
static const int SLOT_SetSize = 30;
static const int SLOT_SetWidth = 31;
static const int SLOT_SetHeight = 32;
static const int SLOT_SetScrollLocation = 33;
static const int SLOT_SetScrollExtent = 34;
static const int SLOT_GetScrollExtent = 35;
static const int SLOT_GetScrollSizes = 36;
static const int SLOT_GetMouseCursor_c = 37;
static const int SLOT_GetMouseCursor = 38;
static const int SLOT_GetLocalTooltip = 39;
static const int SLOT_GetWidgetFromPoint = 40;
static const int SLOT_CanSelect = 41;
static const int SLOT_SetSelected = 42;
static const int SLOT_SetSelectable = 43;
static const int SLOT_SetTabRoot = 44;
static const int SLOT_SetVisible = 45;
static const int SLOT_SetUnderMouse = 46;
static const int SLOT_GetFocusedLeafWidget = 47;
static const int SLOT_WantsMessage = 48;
static const int SLOT_ProcessMessage = 49;
static const int SLOT_ProcessChildNotificationMessage = 50;
static const int SLOT_GetStyle = 51;
static const int SLOT_Render = 52;
static const int SLOT_IsDropOk = 53;
static const int SLOT_GetCustomDragWidget = 54;
static const int SLOT_OnSizeChanged = 55;
static const int SLOT_OnLocationChanged = 56;
static const int SLOT_Page_InsertChildBefore = 57;
static const int SLOT_Page_InsertChildAfter = 58;
static const int SLOT_Page_Pack = 59;
static const int SLOT_Page_slot60 = 60;
static const int SLOT_CuiMediator_saveSettings = 5;

static const int OFF_CreatureObject_group = 0x7B8;  // CachedNetworkId; lea ecx,[esi+0x7B8] before getObject
static const int OFF_GroupObject_membersBegin = 0x2B8;  // std::vector<pair<NetworkId,Unicode::String>>::begin
static const int OFF_GroupObject_membersEnd = 0x2BC;  // the same vector: end; element stride 0x18, the name at +8
static const int OFF_GroupMember_stride = 0x18;  // add esi,0x18 in the loop over group members
static const int OFF_GroupMember_name = 0x08;  // a Unicode::String right after the NetworkId in the pair
static const int OFF_TangibleObject_pvpFlags_slot = 0x28;  // call [vtbl+0xA0] in isAttackable (0x640238)
static const int OFF_TangibleObject_condition = 0x38C;  // the 0x100 bit (invulnerable) check in isAttackable
static const int OFF_CreatureObject_lookAtTarget = 0x598;  // CachedNetworkId; lea ebx,[player+0x598] in cycleTargetsForPlayer, compared in isTargetCycleOk
static const int OFF_Object_transform_posX = 0x0C;  // Transform 3x4 in row order: position at 0x0C/0x1C/0x2C, forward vector at 0x08/0x18/0x28
static const int OFF_UIBaseObject_refcount = 0x04;  // word; Attach/Detach
static const int OFF_UIBaseObject_name = 0x08;  // std::string (MSVC7)
static const int OFF_UIBaseObject_parent = 0x14;  // RemoveFromParent
static const int OFF_UIWidget_location = 0x2C;  // SetLocation
static const int OFF_UIWidget_size = 0x34;  // SetWidth/SetHeight
static const int OFF_UIWidget_scrollLocation = 0x3C;  // SetScrollLocation
static const int OFF_UIWidget_scrollExtent = 0x44;  // GetScrollExtent
static const int OFF_UIWidget_flags = 0x7C;  // CanSelect: bits 0|1 visible, 2 enabled, 8 getsInput
static const int OFF_UIPage_children = 0x104;  // std::list<UIBaseObject*> (ResetLocalizedStrings/Pack)
static const int OFF_UIPage_pageFlags = 0x120;  // Pack: bit 2 = DoNotPackChildren
static const int OFF_UIManager_rootPage = 0x04;  // GetObjectFromPath/GetFocusedLeaf
static const int OFF_UIManager_contextPage = 0xD8;  // PushContextWidget
static const int OFF_UIManager_dragObject = 0x40;  // AbortDrag: non-zero means a drag is in progress
static const int OFF_CuiIoWin_mouseCursor = 0x10;  // warpCursor
static const int OFF_SwgCuiToolbar_volumePage = 0x94;  // ctor 0xF64AE0: getCodeDataObject(0x27, [esi+0x94], "volumePage")
static const int OFF_SwgCuiToolbar_volumeKeyBindings = 0xE4;  // updateKeyBindings: mov ecx,[ecx+0xE4]; GetChildrenRef
static const int OFF_UIMessage_Type = 0x00;  // 
static const int OFF_UIMessage_Modifiers = 0x04;  // 9 bytes
static const int OFF_UIMessage_Keystroke = 0x0E;  // word
static const int OFF_UIMessage_Data = 0x10;  // word
static const int OFF_UIMessage_MouseX = 0x14;  // 
static const int OFF_UIMessage_MouseY = 0x18;  // 
static const int OFF_UIMessage_DragSource = 0x1C;  // 
static const int OFF_UIMessage_DragObject = 0x20;  // 
static const int OFF_UIMessage_DragTarget = 0x24;  // 
static const int OFF_UIMessage_size = 0x28;  // the 0x1124BF0 constructor

enum MsgType {
    MSG_KeyFirst = 0,
    MSG_KeyDown = 1,
    MSG_KeyUp = 2,
    MSG_KeyRepeat = 3,
    MSG_Character = 4,
    MSG_KeyLast = 5,
    MSG_MouseFirst = 6,
    MSG_LeftMouseDown = 7,
    MSG_MiddleMouseDown = 8,
    MSG_RightMouseDown = 9,
    MSG_MouseLastFocusChanger = 10,
    MSG_LeftMouseDoubleClick = 11,
    MSG_MiddleMouseDoubleClick = 12,
    MSG_RightMouseDoubleClick = 13,
    MSG_LeftMouseUp = 14,
    MSG_MiddleMouseUp = 15,
    MSG_RightMouseUp = 16,
    MSG_MouseLastButton = 17,
    MSG_MouseMove = 18,
    MSG_MouseEnter = 19,
    MSG_MouseExit = 20,
    MSG_MouseWheel = 21,
    MSG_ContextRequest = 22,
    MSG_MouseLast = 23,
    MSG_DragFirst = 24,
    MSG_DragStart = 25,
    MSG_DragEnd = 26,
    MSG_DragCancel = 27,
    MSG_DragOver = 28,
    MSG_DragLast = 29,
};

static const uint16_t UIMessage_key_BackSpace_VALUE = 0x1008;
static const uint16_t UIMessage_key_Insert_VALUE = 0x102D;
static const uint16_t UIMessage_key_Delete_VALUE = 0x102E;
static const uint16_t UIMessage_key_LeftArrow_VALUE = 0x1025;
static const uint16_t UIMessage_key_RightArrow_VALUE = 0x1027;
static const uint16_t UIMessage_key_UpArrow_VALUE = 0x1026;
static const uint16_t UIMessage_key_DownArrow_VALUE = 0x1028;
static const uint16_t UIMessage_key_Home_VALUE = 0x1024;
static const uint16_t UIMessage_key_End_VALUE = 0x1023;
static const uint16_t UIMessage_key_PageUp_VALUE = 0x1021;
static const uint16_t UIMessage_key_PageDown_VALUE = 0x1022;
static const uint16_t UIMessage_key_Tab_VALUE = 0x1009;
static const uint16_t UIMessage_key_Space_VALUE = 0x0020;
static const uint16_t UIMessage_key_Enter_VALUE = 0x000D;
static const uint16_t UIMessage_key_Escape_VALUE = 0x001B;

}} // namespace cp::abi
