# -*- coding: utf-8 -*-
"""src/consoleport/abi/props.h out of tools/ui_props.txt: a table of every
UILowerString property-name global in the binary, plus named constants for the ones
the module uses. Add a name to WANTED and regenerate.

    python gen_props.py
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'ui_props.txt')
OUT = os.path.join(HERE, '..', 'src', 'consoleport', 'abi', 'props.h')

WANTED = ['Visible', 'Location', 'LocationX', 'LocationY', 'Size', 'SizeX', 'SizeY', 'Opacity', 'Color',
          'BackgroundColor', 'BackgroundOpacity', 'BackgroundTint', 'PalBgTint', 'PalColor', 'PalText', 'PalTextHighlight', 'SourceRect', 'SourceResource',
          'Style', 'RStyleDefault', 'Icon', 'Text', 'LocalText', 'TextColor', 'Enabled', 'GetsInput', 'AbsorbsInput',
          'Selectable', 'Activated', 'PackLocation', 'PackSize', 'ScrollExtent', 'DoNotPackChildren', 'MaximumSize',
          'MinimumSize', 'Font', 'TextAlignment', 'Name', 'Rotation', 'Focus', 'EffectorExecute', 'EffectorCancel',
          'CellSize', 'CellPadding', 'CellCount', 'CellMax', 'OnPress', 'Press', 'OpacityRelativeMin',
          'CameraYaw', 'LocalTooltip', 'Tooltip']


def load():
    props = {}
    for line in open(SRC, encoding='utf-8'):
        w = line.split()
        if len(w) == 2 and w[1].startswith('0x'):
            props[w[0]] = int(w[1], 16)
    return props


def gen():
    props = load()
    names = sorted(props, key=lambda n: n)
    h = ['// Generated by tools/gen_props.py from tools/ui_props.txt: the UILowerString globals of the property names in swgemu.exe. DO NOT EDIT.',
         '#pragma once', '#include <cstdint>', '', 'namespace cp { namespace abi {', '',
         'struct PropName { const char* name; uint32_t va; };', 'static const PropName PROPS[] = {']
    for n in names:
        h.append('    {"%s", 0x%08X},' % (n, props[n]))
    h += ['};', 'static const int PROPS_COUNT = %d;' % len(names), '']
    missing = [n for n in WANTED if n not in props]
    if missing:
        raise SystemExit('not in ui_props.txt: %s' % missing)
    for n in WANTED:
        h.append('static const uint32_t PROP_%s = 0x%08X;' % (n, props[n]))
    h += ['', '}} // namespace cp::abi']
    open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(h) + '\n')
    print('->', os.path.normpath(OUT), len(names), 'properties,', len(WANTED), 'constants')


if __name__ == '__main__':
    gen()
