# -*- coding: utf-8 -*-
"""Generating src/consoleport/gen/profiles.h from layout.py: the pad profiles,
the hook slot model, the modifier bits, the scancodes. The single source of truth is
layout.py; the module and the layout files read one table.

    python gen_profiles.py
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import layout as L

OUT = os.path.join(HERE, '..', 'src', 'consoleport', 'gen', 'profiles.h')
BUTTONS = ['CROSS', 'CIRCLE', 'SQUARE', 'TRIANGLE', 'L1', 'R1', 'L2', 'R2',
           'SHARE', 'OPTIONS', 'L3', 'R3', 'PS', 'PAD',
           'DPAD_UP', 'DPAD_DOWN', 'DPAD_LEFT', 'DPAD_RIGHT']
DPAD_JOYB = L.DPAD_JOYB   # synthesized by the module out of the POV


def gen():
    h = ['// Generated by tools/gen_profiles.py from tools/layout.py. DO NOT EDIT BY HAND.',
         '#pragma once', '', 'namespace cp { namespace gen {', '',
         '// logical pad buttons (the index into Profile::joyb)',
         'enum Button {']
    for i, b in enumerate(BUTTONS):
        h.append('    B_%s = %d,' % (b, i))
    h += ['    B_COUNT = %d' % len(BUTTONS), '};', '',
          'struct Profile { const char* name; int joyb[B_COUNT]; bool triggersAsButtons; };',
          '// -1 = this profile has no such button (through Steam Input the triggers arrive',
          '// as axes or keys)',
          'static const Profile PROFILES[] = {']
    for name, pr in L.PROFILES.items():
        joy = dict(pr['joy'])
        joy.update(DPAD_JOYB)
        vals = [joy.get(b) if joy.get(b) is not None else -1 for b in BUTTONS]
        h.append('    {"%s", {%s}, %s},' % (name, ', '.join('%d' % v for v in vals),
                                             'true' if pr['triggers_as_buttons'] else 'false'))
    h += ['};', 'static const int PROFILE_COUNT = %d;' % len(L.PROFILES), '',
          '// the buttons the module synthesizes: the triggers, and the D-pad out of the POV',
          'static const int JOYB_TRIGGER_L2 = %d;' % L.TRIGGER_JOYB['hook']['L2'],
          'static const int JOYB_TRIGGER_R2 = %d;' % L.TRIGGER_JOYB['hook']['R2']]
    for k, v in DPAD_JOYB.items():
        h.append('static const int JOYB_%s = %d;' % (k, v))
    h += ['', "// the input map's SHFT bits for the modifiers"]
    for m, bit in L.MOD_BITS.items():
        h.append('static const unsigned MODBIT_%s = 0x%02X;' % (m, bit))
    h += ['', '// DirectInput scancodes of the key duplicates (D-pad and triggers through Steam Input)']
    for k, v in L.KEY.items():
        h.append('static const int KEY_%s = %d;  // %s' % (k, v, L.KEYNAME[v]))
    h += ['', '// A crossbar position. THE SET IS THE TOOLBAR PANE, not the slot number: a pane',
          '// holds 24 slots and as many CuiDragInfo, so the forty assignments live across',
          '// panes while a position keeps one slot.',
          'enum Fan { FAN_UP = 0, FAN_LEFT = 1, FAN_RIGHT = 2, FAN_DOWN = 3 };',
          '// pane = set; 4 and 5 are left to the player',
          'enum Pane { PANE_MAIN = 0, PANE_L2 = 1, PANE_R2 = 2, PANE_L2R2 = 3, PANE_SET_COUNT = 4 };',
          '// cross: 0 D-pad, 1 face buttons, EXTRA_CROSS is the L3/R3 block in the middle',
          'struct Cluster { Button button; Fan fan; int cross; int slot; };',
          'static const int CLUSTER_COUNT = %d;' % len(L.HOOK_POSITIONS),
          'static const int CROSS_COUNT = 2;      // there are two plus-shaped crosses',
          'static const int EXTRA_CROSS = 2;      // the marker of the L3/R3 block',
          'static const int EXTRA_COUNT = %d;' % sum(1 for b in L.HOOK_POSITIONS if b in ('L3', 'R3')),
          'static const Cluster CLUSTERS[CLUSTER_COUNT] = {']
    for b in L.HOOK_POSITIONS:
        cross = 0 if b.startswith('DPAD') else (2 if b in ('L3', 'R3') else 1)
        h.append('    {B_%s, FAN_%s, %d, %d},' % (b, L.FAN_DIR[b], cross, L.hook_slot_of(b)))
    h += ['};', 'static const int SLOT_COUNT = %d;' % L.hook_slot_count(), '',
          '// PS5 face button colors (ConsolePort PlayStation5.lua) and those of the rest']
    for b in L.HOOK_POSITIONS:
        h.append('static const char COLOR_%s[] = "%s";' % (b, L.FACE_COLOR.get(b, L.DPAD_COLOR)))
    # The trigger glyphs are the one entry here that follows the client's theme, so the
    # generator emits the palette name plus the reason. Until 10 Sep 2026 this line
    # carried L.MOD_COLOR (a hex value) and the generator silently regressed the header
    # after the theme work; layout.MOD_COLOR is kept only as the fallback shade.
    h += ['// L2/R2 have no colour of their own the way the face buttons do, so the trigger',
          '// glyphs follow the interface theme - the one palette entry in this list',
          '// (core/theme.h).',
          'static const char COLOR_MOD[] = "%s";' % L.MOD_PALETTE, '', '}} // namespace cp::gen']
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(h) + '\n')
    print('->', os.path.normpath(OUT))


if __name__ == '__main__':
    gen()
